### ISSUE TITLE
Add needrestart?

### ISSUE THREAD

**Issue by ypid** [debops/ansible-apt_install#6]
Just rechecked because of the OpenSSL patch and saw that [`needrestart`](https://packages.debian.org/search?keywords=needrestart) is not installed by default? I have been using it from [`ypid.packages`](https://github.com/ypid/ansible-packages).

Just noticed that there is a newer version for jessie in backports. I have not yet checked if that might be useful.

**Comment by drybjed** [comment]
Does the package offer some configuration / overrides? I'll check it out and maybe add support for it in `debops.apt` role if it's not too big.

**Comment by ypid** [comment]
@drybjed Can be configured under `/etc/needrestart` but I did not need to change something there yet. If you want to cover that, I would suggest to create `debops.needrestart`.

**Comment by drybjed** [comment]
It looks like `needrestart` has some extensive configuration, a separate role might be a better idea. We could even go for version from `jessie-backports` by default which apparently supports mail notification (sadly disabled by default).

**Comment by ypid** [comment]
Seems `needrestart` in jessie does not handle processes running in LXC containers correctly. The version in `jessie-backports` should fix that. I am currently using:

```YAML
  - package: 'needrestart'
    reason: 'Properly handle LXC or other containers.'
    backports: [ 'jessie' ]
```

**Comment by drybjed** [comment]
Good catch with the backport requirement. Do you think that installing the package only is sufficient, or is it worth creating a separate role for it?

**Comment by ypid** [comment]
@drybjed As mentioned above, I did not feel the need to make any custom configuration to it. But I would not say no to a debops.needrestart role just in case :wink:
