### ISSUE TITLE
gnupg-curl is not available for install in Debian stretch, yakkety

### ISSUE THREAD

**Issue by jbicha** [debops/ansible-apt_install#9]
Neither Debian stretch nor Ubuntu 16.10 "yakkety" have the gnupg-curl package available any more. There is a gnupg1-curl package but gnupg2 is the default gnupg now so it would better to avoid gnupg1 if it's not too much trouble.

https://github.com/debops/ansible-apt_install/blob/master/defaults/main.yml#L110

`TASK [debops.apt_install : Install requested APT packages] *********************
failed: [amy01.com] (item=[u'ed', u'lsb-release', u'make', u'sudo', u'gnupg-curl', u'git', u'curl', u'rsync', u'bsdutils', u'acl', u'python', u'python-apt', u'python-pip', u'python-pycurl', u'python-httplib2', u'ncurses-term', u'zsh', u'tmux', u'less', u'file', u'psmisc', u'lsof', u'tree', u'htop', u'iftop', u'nload', u'nmon', u'mtr-tiny', u'mc', u'ranger', u'vim', u'libpam-systemd', u'haveged']) => {"failed": true, "item": ["ed", "lsb-release", "make", "sudo", "gnupg-curl", "git", "curl", "rsync", "bsdutils", "acl", "python", "python-apt", "python-pip", "python-pycurl", "python-httplib2", "ncurses-term", "zsh", "tmux", "less", "file", "psmisc", "lsof", "tree", "htop", "iftop", "nload", "nmon", "mtr-tiny", "mc", "ranger", "vim", "libpam-systemd", "haveged"], "msg": "No package matching 'gnupg-curl' is available"}`

**Comment by drybjed** [comment]
Thanks for the heads up! The `debops.apt_install` role allows for conditional package installation, so support for different distributions and releases for this is definitely possible. I'll look into making a specific condition for GnuPG packages to take care of this.

**Comment by egon0** [comment]
Haha, just reported this issue some minutes ago at IRC 😎
